name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.9']
        poetry-version: ['1.1.6']
        pip-version: ['21.1.1']
    steps:
      - uses: actions/checkout@v2
      - name: Setup, Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Deploy with Python ${{ matrix.python-version }}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          # Set up Python
          python -m pip install --upgrade pip==${{ matrix.pip-version }}
          # Set up Poetry
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
          python get-poetry.py
          rm get-poetry.py
          source "$HOME/.poetry/env"
          poetry self update ${{ matrix.poetry-version }}
          # Release with Poetry
          poetry build
          poetry publish --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
